# Detekt configuration (baseline for Kotlin + Jetpack Compose)
# Projects can copy this and customize locally.

build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true

processors:
  active: true

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'   # keep summary concise in CI
    - 'FileBasedFindingsReport'

output-reports:
  active: true

comments:
  AbsentOrWrongFileLicense:
    active: false

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '100', '200']
    ignoreHashCodeFunction: true
  WildcardImport:
    active: true
    excludeImports:
      - 'java.util.*'
      - 'kotlinx.coroutines.*'
      - 'androidx.compose.*'   # compose often expands many symbols
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludePackageStatements: true
    excludeImportStatements: true
  UnusedImports:
    active: true
  ReturnCount:
    active: true
    max: 3
    excludedFunctions:
      - 'equals'
      - 'hashCode'
      - 'onCreate'
      - 'onStart'
      - 'onResume'
  DataClassShouldBeImmutable:
    active: true

naming:
  active: true
  ClassNaming:
    active: true
    excludes: ['**/preview/**', '**/*Preview*.*']
  FunctionNaming:
    active: true
    # Allow @Composable PascalCase functions used as UI components
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  TopLevelPropertyNaming:
    active: true

complexity:
  active: true
  LongParameterList:
    active: true
    threshold: 8
    ignoreAnnotated: ['Composable']
  LongMethod:
    active: true
    threshold: 80
  LargeClass:
    active: true
    threshold: 600
  TooManyFunctions:
    active: true
    thresholdInClasses: 25
    thresholdInFiles: 30

performance:
  active: true

potential-bugs:
  active: true
  CastToNullableType:
    active: true
  IncorrectScopeFunctions:
    active: true

coroutines:
  active: true

compose:
  active: true
  CompositionLocalAllowlist:
    active: false

configurations:
  excludes: ['**/build/**', '**/.gradle/**', '**/generated/**', '**/test/**', '**/androidTest/**', '**/resources/**']

# Report formats (Gradle detekt task can also configure these)
reports:
  txt:
    enabled: true
    destination: build/reports/detekt/detekt.txt
  xml:
    enabled: true
    destination: build/reports/detekt/detekt.xml
  html:
    enabled: true
    destination: build/reports/detekt/detekt.html
  sarif:
    enabled: true
    destination: build/reports/detekt/detekt.sarif.json
