#!/usr/bin/env bash
set -euo pipefail

# Compose a GitHub Actions job summary in Markdown using other script outputs.
# Inputs (optional):
#   COVERAGE_TXT: line like "Coverage: 78.23%"
#   LINT_TXT:     line like "Detekt: 12 issues"
#   JUNIT_TXT:    line like "JUnit: total=120, passed=118, failed=2, skipped=0"

COVERAGE_TXT="${COVERAGE_TXT:-}"
LINT_TXT="${LINT_TXT:-}"
JUNIT_TXT="${JUNIT_TXT:-}"

SUMMARY_FILE="${GITHUB_STEP_SUMMARY:-/tmp/job-summary.md}"

{
  echo "## 🧪 CI Summary"
  echo
  if [[ -n "${JUNIT_TXT}" ]]; then
    echo "- ${JUNIT_TXT}"
  fi
  if [[ -n "${COVERAGE_TXT}" ]]; then
    echo "- ${COVERAGE_TXT}"
  fi
  if [[ -n "${LINT_TXT}" ]]; then
    echo "- ${LINT_TXT}"
  fi
  echo
  echo "> _Generated by tool/scripts/generate_summary_md.sh_"
} >> "${SUMMARY_FILE}"

echo "Summary written to ${SUMMARY_FILE}"
