name: "Setup Android Environment"
description: "Installs and configures Android SDK, platform tools, and verifies environment setup."

inputs:
  java_version:
    required: true
    description: "Java version to install (e.g., 17)"

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Java (Temurin)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        cache: gradle

    - name: Install Android SDK
      shell: bash
      run: bash $GITHUB_ACTION_PATH/install_sdk.sh

    - name: Verify Environment Setup
      shell: bash
      run: bash $GITHUB_ACTION_PATH/verify_env.sh

    - name: Ensure Gradlew Executable & Wrapper Exists
      shell: bash
      run: |
        chmod +x gradlew || true
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          echo "⚙️ Gradle wrapper not found — generating..."
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew
        fi

        echo "✅ Gradle wrapper verified."

    - name: Confirm Android SDK Path
      shell: bash
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        echo "✅ Android SDK setup complete."
